# Generated by Django 5.2.8 on 2025-11-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioAnaliseRelacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_inicio', models.DateTimeField(auto_now_add=True)),
                ('nome_analise', models.CharField(max_length=200)),
                ('tabelas_envolvidas', models.CharField(max_length=200)),
                ('total_registros_analisados', models.BigIntegerField()),
                ('total_inconsistencias', models.BigIntegerField()),
                ('percentual_consistencia', models.FloatField()),
                ('descricao_impacto', models.TextField()),
                ('exemplos_inconsistencias', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
