# Generated by Django 5.2.8 on 2025-11-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises_relacionais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioDQI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('score_total', models.FloatField()),
                ('score_completude', models.FloatField()),
                ('score_validade', models.FloatField()),
                ('score_unicidade', models.FloatField()),
                ('score_consistencia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioRiscoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_contas', models.IntegerField()),
                ('faixa_verde_90dias', models.IntegerField()),
                ('faixa_amarela_180dias', models.IntegerField()),
                ('faixa_vermelha_1ano', models.IntegerField()),
                ('faixa_critica_velha', models.IntegerField()),
            ],
        ),
    ]
