# Generated by Django 5.2.8 on 2025-11-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioCompletude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_execucao', models.DateTimeField(auto_now_add=True)),
                ('total_usuarios', models.IntegerField()),
                ('sem_gerente', models.IntegerField()),
                ('sem_departamento', models.IntegerField()),
                ('sem_cargo', models.IntegerField()),
                ('contato_completo', models.IntegerField()),
                ('perc_sem_gerente', models.FloatField()),
                ('perc_sem_departamento', models.FloatField()),
                ('perc_sem_cargo', models.FloatField()),
                ('perc_contato_completo', models.FloatField()),
            ],
        ),
    ]
