# Generated by Django 5.2.8 on 2025-11-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises_simples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioCompletudeGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_execucao', models.DateTimeField(auto_now_add=True)),
                ('tabela_analisada', models.CharField(max_length=100)),
                ('total_registros', models.BigIntegerField()),
                ('total_colunas', models.BigIntegerField()),
                ('total_celulas', models.BigIntegerField()),
                ('total_celulas_preenchidas', models.BigIntegerField()),
                ('percentual_completude_geral', models.FloatField()),
                ('relatorio_colunas_vazias', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
