# Generated by Django 5.2.8 on 2025-11-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises_simples', '0002_relatoriocompletudegeral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatoriocompletudegeral',
            old_name='timestamp_execucao',
            new_name='timestamp_inicio',
        ),
        migrations.RemoveField(
            model_name='relatoriocompletudegeral',
            name='tabela_analisada',
        ),
        migrations.AddField(
            model_name='relatoriocompletudegeral',
            name='timestamp_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
