# Generated by Django 5.2.8 on 2025-11-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises_simples', '0003_rename_timestamp_execucao_relatoriocompletudegeral_timestamp_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriocompletudegeral',
            name='tabela_analisada',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
