# Generated by Django 5.2.8 on 2025-11-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises_simples', '0004_relatoriocompletudegeral_tabela_analisada'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioValidadeFormato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_execucao', models.DateTimeField(auto_now_add=True)),
                ('tabela_analisada', models.CharField(max_length=100)),
                ('total_celulas_preenchidas', models.BigIntegerField()),
                ('total_celulas_invalidas', models.BigIntegerField()),
                ('total_celulas_vazias', models.BigIntegerField()),
                ('percentual_validade', models.FloatField()),
                ('detalhamento_erros', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
