# Generated by Django 5.2.8 on 2025-11-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises_simples', '0005_relatoriovalidadeformato'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioUnicidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_execucao', models.DateTimeField(auto_now_add=True)),
                ('tabela_analisada', models.CharField(max_length=100)),
                ('coluna_analisada', models.CharField(max_length=100)),
                ('total_registros', models.BigIntegerField()),
                ('registros_vazios', models.BigIntegerField()),
                ('registros_preenchidos', models.BigIntegerField()),
                ('registros_unicos_preenchidos', models.BigIntegerField()),
                ('percentual_unicidade', models.FloatField()),
            ],
        ),
    ]
