# Generated by Django 5.2.8 on 2025-11-13 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analises_simples', '0006_relatoriounicidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatoriocompletude',
            old_name='timestamp_execucao',
            new_name='timestamp_inicio',
        ),
        migrations.RenameField(
            model_name='relatoriounicidade',
            old_name='timestamp_execucao',
            new_name='timestamp_inicio',
        ),
        migrations.RenameField(
            model_name='relatoriovalidadeformato',
            old_name='timestamp_execucao',
            new_name='timestamp_inicio',
        ),
    ]
