# Generated by Django 5.2.8 on 2025-11-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises_simples', '0007_rename_timestamp_execucao_relatoriocompletude_timestamp_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioUnicidadeGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_inicio', models.DateTimeField(auto_now_add=True)),
                ('tabela_analisada', models.CharField(max_length=100)),
                ('total_registros', models.BigIntegerField()),
                ('total_colunas_analisadas', models.IntegerField()),
                ('media_unicidade', models.FloatField()),
                ('qtd_colunas_com_duplicatas', models.IntegerField()),
                ('detalhe_por_coluna', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
