# Generated by Django 5.2.8 on 2025-11-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises_simples', '0008_relatoriounicidadegeral'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioRegraNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_inicio', models.DateTimeField(auto_now_add=True)),
                ('nome_regra', models.CharField(max_length=200)),
                ('dimensao', models.CharField(max_length=50)),
                ('tabela_analisada', models.CharField(max_length=100)),
                ('tipo_tabela', models.CharField(max_length=20)),
                ('qtd_total_registros', models.BigIntegerField()),
                ('qtd_falhas', models.BigIntegerField()),
                ('percentual_falha', models.FloatField()),
                ('descricao_impacto', models.TextField()),
                ('exemplos_falhas', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
