# Generated by Django 5.2.8 on 2025-11-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises_simples', '0009_relatorioregranegocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioUnicidadePersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_inicio', models.DateTimeField(auto_now_add=True)),
                ('tabela_analisada', models.CharField(max_length=100)),
                ('colunas_combinadas', models.CharField(max_length=500)),
                ('total_registros', models.BigIntegerField()),
                ('registros_unicos', models.BigIntegerField()),
                ('registros_duplicados', models.BigIntegerField()),
                ('percentual_unicidade', models.FloatField()),
                ('exemplos_duplicatas', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
