# Generated by Django 5.2.8 on 2025-11-11 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_inicio', models.DateTimeField(auto_now_add=True)),
                ('timestamp_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('INICIADO', 'Iniciado'), ('EM_PROGRESSO', 'Em Progresso'), ('CONCLUIDO', 'Concluído'), ('FALHOU', 'Falhou')], default='INICIADO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LogEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_nome', models.CharField(choices=[('ETAPA_1_EXTRACAO', 'Etapa 1: Extração AD'), ('ETAPA_2_LIMPEZA', 'Etapa 2: Limpeza de CSVs'), ('ETAPA_3_PREPARACAO_BANCO', 'Etapa 3: Preparação do Banco'), ('ETAPA_4_CARGA_STAGING', 'Etapa 4: Carga para Staging'), ('ETAPA_5_TRANSFORMACAO', 'Etapa 5: Transformação (Produção)'), ('ETAPA_DESCONHECIDA', 'Etapa Desconhecida')], max_length=50)),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('FALHOU', 'Falhou')], max_length=20)),
                ('timestamp_inicio', models.DateTimeField()),
                ('timestamp_fim', models.DateTimeField()),
                ('resumo_execucao', models.TextField(blank=True, null=True)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_etapas', to='qualidade_ad.execucaopipeline')),
            ],
        ),
    ]
